# Generated by Django 2.1.5 on 2019-10-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='original',
        ),
    ]
