# Generated by Django 2.1.5 on 2019-10-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_remove_leave_original'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='name',
            new_name='dept_name',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='time_approved',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='time_received',
        ),
    ]
