# Generated by Django 2.1.5 on 2019-10-22 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_auto_20191022_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
