# Generated by Django 2.1.5 on 2019-10-22 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_app', '0004_auto_20191022_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leave',
            new_name='leave_model',
        ),
    ]
