# Generated by Django 2.1.5 on 2019-11-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_auto_20191022_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
