# Generated by Django 2.1.5 on 2019-11-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0007_auto_20191115_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_model',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
