# Generated by Django 2.1.5 on 2019-11-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0008_auto_20191115_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_model',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
