# Generated by Django 2.1.5 on 2019-11-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0009_auto_20191115_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_model',
            name='leave_type',
            field=models.IntegerField(choices=[(1, 'Casual Leave'), (2, 'Half Pay Leave'), (3, 'Commuted Leave')], default=1),
        ),
    ]
