# Generated by Django 2.1.5 on 2019-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0010_leave_model_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_model',
            name='date_from',
            field=models.DateField(),
        ),
    ]
